name: Build Kernel 4.19

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git wget curl unzip bc bison flex \
            libssl-dev build-essential ccache \
            gcc-aarch64-linux-gnu \
            gcc-arm-linux-gnueabi \
            device-tree-compiler \
            python3 xz-utils zip cpio

      - name: Run build script
        run: |
          chmod +x build.sh
          ./build.sh
